[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache for 1 year

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache for 1 year

[[headers]]
  for = "/assets/favicon/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache for 1 year
